import pyqtgraph as pg

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph.widgets.PlotWidget import PlotWidget


import matplotlib as mpl
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from mpl_toolkits.axes_grid import make_axes_locatable
import matplotlib.pyplot as plt


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.pincipalPage = QtWidgets.QWidget()
        self.pincipalPage.setObjectName("pincipalPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pincipalPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.pincipalPage)
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainGraph = PlotWidget(self.verticalLayoutWidget)
        self.mainGraph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainGraph.setObjectName("mainGraph")
        self.verticalLayout.addWidget(self.mainGraph)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")



        self.timer = QtCore.QTimer()
        self.timer.setInterval(17)


        self.figure = Figure()
        self.axes = self.figure.add_subplot(2, 1, 1)
        self.divider = make_axes_locatable(self.axes)
        self.norm = mpl.colors.Normalize(vmin=0, vmax=10)
        self.c_bar_ax = self.divider.append_axes('right', size='5%', pad=0.4)
        self.canvas = FigureCanvas(self.figure)
        self.figure.tight_layout()
        self.verticalLayout_2.addWidget(self.canvas)
        self.gridLayout_2.addWidget(self.splitter, 0, 2, 28, 1)


        ###
        self.horizontalSlider_volume = QtWidgets.QSlider(self.pincipalPage)
        self.horizontalSlider_volume.setProperty("value", 50)
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        #self.gridLayout.addWidget(self.horizontalSlider_volume,22, 0, 1, 1)
        self.horizontalSlider_volume.setMinimum(1)
        self.horizontalSlider_volume.setMaximum(100)
        self.horizontalSlider_volume.setSingleStep(20)
        self.horizontalSlider_volume.setValue(50)
        self.gridLayout_2.addWidget(self.horizontalSlider_volume, 22, 0, 1, 1)

        #
        self.volumeLabel = QtWidgets.QLabel(self.pincipalPage)
        self.gridLayout_2.addWidget(self.volumeLabel, 22, 1, 1, 1)
        self.volumeLabel.setObjectName("volumeLabel")
        self.volumeLabel.setText("volumeL")


        self.drums = QtWidgets.QSlider(self.pincipalPage)
        self.drums.setMaximumSize(QtCore.QSize(200, 20))
        self.drums.setOrientation(QtCore.Qt.Horizontal)
        self.drums.setObjectName("drums")
        self.drums.setMinimum(0)
        self.drums.setValue(1)
        self.drums.setMaximum(10)
        self.gridLayout_2.addWidget(self.drums, 9, 0, 1, 1)
        self.piano = QtWidgets.QSlider(self.pincipalPage)
        self.piano.setMinimumSize(QtCore.QSize(200, 20))
        self.piano.setMaximumSize(QtCore.QSize(200, 20))
        self.piano.setOrientation(QtCore.Qt.Horizontal)
        self.piano.setObjectName("piano")
        self.piano.setMinimum(0)
        self.piano.setValue(1)
        self.piano.setMaximum(10)
        self.gridLayout_2.addWidget(self.piano, 5, 0, 1, 1)
        self.saxophone = QtWidgets.QSlider(self.pincipalPage)
        self.saxophone.setMaximumSize(QtCore.QSize(200, 20))
        self.saxophone.setOrientation(QtCore.Qt.Horizontal)
        self.saxophone.setObjectName("saxophone")
        self.saxophone.setMinimum(0)
        self.saxophone.setValue(1)
        self.saxophone.setMaximum(10)
        self.gridLayout_2.addWidget(self.saxophone, 12, 0, 1, 1)
        self.violin = QtWidgets.QSlider(self.pincipalPage)
        self.violin.setMaximumSize(QtCore.QSize(200, 20))
        self.violin.setOrientation(QtCore.Qt.Horizontal)
        self.violin.setObjectName("violin")
        self.violin.setMinimum(0)
        self.violin.setValue(1)
        self.violin.setMaximum(10)
        self.gridLayout_2.addWidget(self.violin, 15, 0, 1, 1)
        self.Xylophone = QtWidgets.QSlider(self.pincipalPage)
        self.Xylophone.setMaximumSize(QtCore.QSize(200, 20))
        self.Xylophone.setOrientation(QtCore.Qt.Horizontal)
        self.Xylophone.setObjectName("Xylophone")
        self.Xylophone.setMinimum(0)
        self.Xylophone.setValue(1)
        self.Xylophone.setMaximum(10)
        self.gridLayout_2.addWidget(self.Xylophone, 18, 0, 1, 1)
        self.pian = QtWidgets.QToolButton(self.pincipalPage)
        self.pian.setMaximumSize(QtCore.QSize(25, 20))
        self.pian.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pian.setIcon(icon)
        self.pian.setObjectName("pian")
        self.gridLayout_2.addWidget(self.pian, 9, 1, 1, 1)
        self.sax = QtWidgets.QToolButton(self.pincipalPage)
        self.sax.setMaximumSize(QtCore.QSize(25, 20))
        self.sax.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("saxophone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sax.setIcon(icon)
        self.sax.setObjectName("sax")
        self.gridLayout_2.addWidget(self.sax, 18, 1, 1, 1)
        self.drum = QtWidgets.QToolButton(self.pincipalPage)
        self.drum.setMaximumSize(QtCore.QSize(25, 20))
        self.drum.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("drums.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drum.setIcon(icon)
        self.drum.setObjectName("drum")
        self.gridLayout_2.addWidget(self.drum, 5, 1, 1, 1)
        self.vio = QtWidgets.QToolButton(self.pincipalPage)
        self.vio.setMaximumSize(QtCore.QSize(25, 20))
        self.vio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("violin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vio.setIcon(icon)
        self.vio.setObjectName("vio")
        self.gridLayout_2.addWidget(self.vio, 15, 1, 1, 1)
        self.xylo = QtWidgets.QToolButton(self.pincipalPage)
        self.xylo.setMaximumSize(QtCore.QSize(25, 20))
        self.xylo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("xylophone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xylo.setIcon(icon)
        self.xylo.setObjectName("xylo")
        self.gridLayout_2.addWidget(self.xylo, 12, 1, 1, 1)
        self.load = QtWidgets.QPushButton(self.pincipalPage)
        self.load.setMaximumSize(QtCore.QSize(100, 20))
        self.load.setObjectName("load")
        self.gridLayout_2.addWidget(self.load, 0, 0, 1, 1)
        self.play = QtWidgets.QPushButton(self.pincipalPage)
        self.play.setMaximumSize(QtCore.QSize(100, 20))
        self.play.setObjectName("play")
        self.gridLayout_2.addWidget(self.play, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pincipalPage, "")
        self.secondaryPage = QtWidgets.QWidget()
        self.secondaryPage.setObjectName("secondaryPage")
        self.singer = QtWidgets.QLabel(self.secondaryPage)
        self.singer.setGeometry(QtCore.QRect(60, 100, 251, 371))
        self.singer.setText("")
        self.singer.setPixmap(QtGui.QPixmap("singer.jpeg"))
        self.singer.setScaledContents(True)
        self.singer.setObjectName("singer")
        self.guitar = QtWidgets.QLabel(self.secondaryPage)
        self.guitar.setGeometry(QtCore.QRect(410, 330, 361, 201))
        self.guitar.setText("")
        self.guitar.setPixmap(QtGui.QPixmap("guitar.jpeg"))
        self.guitar.setScaledContents(True)
        self.guitar.setObjectName("guitar")
        self.PW2 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW2.setGeometry(QtCore.QRect(480, 10, 41, 121))
        self.PW2.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW2.setText("")
        self.PW2.setObjectName("PW2")
        self.PW7 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW7.setGeometry(QtCore.QRect(680, 10, 41, 121))
        self.PW7.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW7.setText("")
        self.PW7.setObjectName("PW7")
        self.PW6 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW6.setGeometry(QtCore.QRect(640, 10, 41, 121))
        self.PW6.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW6.setText("")
        self.PW6.setObjectName("PW6")
        self.PW5 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW5.setGeometry(QtCore.QRect(600, 10, 41, 121))
        self.PW5.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW5.setText("")
        self.PW5.setObjectName("PW5")
        self.PW4 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW4.setGeometry(QtCore.QRect(560, 10, 41, 121))
        self.PW4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW4.setText("")
        self.PW4.setObjectName("PW4")
        self.PW3 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW3.setGeometry(QtCore.QRect(520, 10, 41, 121))
        self.PW3.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW3.setText("")
        self.PW3.setObjectName("PW3")
        self.PB2 = QtWidgets.QPushButton(self.secondaryPage)
        self.PB2.setGeometry(QtCore.QRect(510, 10, 21, 81))
        self.PB2.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PB2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PB2.setText("")
        self.PB2.setObjectName("PB2")
        self.PB5 = QtWidgets.QPushButton(self.secondaryPage)
        self.PB5.setGeometry(QtCore.QRect(670, 10, 21, 81))
        self.PB5.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PB5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PB5.setText("")
        self.PB5.setObjectName("PB5")
        self.PB4 = QtWidgets.QPushButton(self.secondaryPage)
        self.PB4.setGeometry(QtCore.QRect(630, 10, 21, 81))
        self.PB4.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PB4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PB4.setText("")
        self.PB4.setObjectName("PB4")
        self.PB3 = QtWidgets.QPushButton(self.secondaryPage)
        self.PB3.setGeometry(QtCore.QRect(550, 10, 21, 81))
        self.PB3.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PB3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PB3.setText("")
        self.PB3.setObjectName("PB3")
        self.PW1 = QtWidgets.QPushButton(self.secondaryPage)
        self.PW1.setGeometry(QtCore.QRect(440, 10, 41, 121))
        self.PW1.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PW1.setText("")
        self.PW1.setObjectName("PW1")
        self.PB1 = QtWidgets.QPushButton(self.secondaryPage)
        self.PB1.setGeometry(QtCore.QRect(470, 10, 21, 81))
        self.PB1.setMaximumSize(QtCore.QSize(1000, 1000))
        self.PB1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PB1.setText("")
        self.PB1.setObjectName("PB1")
        self.label = QtWidgets.QLabel(self.secondaryPage)
        self.label.setGeometry(QtCore.QRect(380, 180, 171, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("dr.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.secondaryPage)
        self.label_2.setGeometry(QtCore.QRect(650, 180, 171, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("drums.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.D1 = QtWidgets.QPushButton(self.secondaryPage)
        self.D1.setGeometry(QtCore.QRect(440, 220, 61, 31))
        self.D1.setText("")
        self.D1.setObjectName("D1")
        self.D2 = QtWidgets.QPushButton(self.secondaryPage)
        self.D2.setGeometry(QtCore.QRect(710, 230, 61, 31))
        self.D2.setText("")
        self.D2.setObjectName("D2")
        self.G4 = QtWidgets.QPushButton(self.secondaryPage)
        self.G4.setGeometry(QtCore.QRect(680, 410, 61, 31))
        self.G4.setText("")
        self.G4.setObjectName("G4")
        self.G3 = QtWidgets.QPushButton(self.secondaryPage)
        self.G3.setGeometry(QtCore.QRect(610, 410, 61, 31))
        self.G3.setText("")
        self.G3.setObjectName("G3")
        self.G2 = QtWidgets.QPushButton(self.secondaryPage)
        self.G2.setGeometry(QtCore.QRect(540, 410, 61, 31))
        self.G2.setText("")
        self.G2.setObjectName("G2")
        self.G1 = QtWidgets.QPushButton(self.secondaryPage)
        self.G1.setGeometry(QtCore.QRect(470, 410, 61, 31))
        self.G1.setText("")
        self.G1.setObjectName("G1")
        self.tabWidget.addTab(self.secondaryPage, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pian.setText(_translate("MainWindow", "..."))
        self.sax.setText(_translate("MainWindow", "..."))
        self.drum.setText(_translate("MainWindow", "..."))
        self.vio.setText(_translate("MainWindow", "..."))
        self.xylo.setText(_translate("MainWindow", "..."))
        self.load.setText(_translate("MainWindow", "Load"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pincipalPage), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.secondaryPage), _translate("MainWindow", "Tab 2"))
#import photo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

